### ISSUE TITLE
unused argument (mc.cores = 1)

### ISSUE THREAD

**Issue by davin777** [dr-rodriguez/Twitter-Analysis-Shiny-App#2]
i just run it and that error came up, help please ?

Warning: Error in FUN: unused argument (mc.cores = 1)
Stack trace (innermost first):
    123: tm_map.SimpleCorpus
    122: tm_map
    121: function_list[[i]]
    120: freduce
    119: _fseq
    118: eval
    117: eval
    116: withVisible
    115: %>%
    114: getTextData [C:\Users\nyvad\Google Drive\R-API\Twitter-Analysis-Shiny-App-master/global.R#79]
    113: <reactive:textdata> [C:\Users\nyvad\Google Drive\R-API\Twitter-Analysis-Shiny-App-master/server.R#29]
    102: textdata
    101: rngfunc
    100: wordcloud_rep
     99: renderPlot [C:\Users\nyvad\Google Drive\R-API\Twitter-Analysis-Shiny-App-master/server.R#60]
     89: <reactive:plotObj>
     78: plotObj
     77: origRenderFunc
     76: output$plot
      1: shiny::runApp

i am not modifying anything at all, just run it and error = unused argument (mc.cores = 1)

**Comment by dr-rodriguez** [comment]
Can you try removing mc.cores=1 from that call and see if that works? It's possible this was required on my machine but is not universally required.

**Comment by davin777** [comment]
more error and weirder...
Warning: Error in iconv: embedded nul in string: 'Merdeka Special f\024<c9$f\004<c80f\b<c9#f\024<c9$f\b<c9%c <c89f\024<c9$f\004<c80f\b<c9#f\024<c9$f\b<c9%c <c89f\024<c9$f\004<c80f\b<c9#f\024<c9$f\b<c9%c <c89\nNike Airmax Thea\nSize 3645\nPrice RM120 including postage \n\nAdd RM10 forb\0& httpstcoEUCO3QGUKi'

Stack trace (innermost first):
    125: iconv
    124: FUN [C:\Users\nyvad\Google Drive\R-API\Twitter-Analysis-Shiny-App-master/global.R#83]
    123: tm_map.SimpleCorpus
    122: tm_map
    121: function_list[[i]]
    120: freduce
    119: _fseq
    118: eval
    117: eval
    116: withVisible
    115: %>%
    114: getTextData [C:\Users\nyvad\Google Drive\R-API\Twitter-Analysis-Shiny-App-master/global.R#79]
    113: <reactive:textdata> [C:\Users\nyvad\Google Drive\R-API\Twitter-Analysis-Shiny-App-master/server.R#29]
    102: textdata
    101: rngfunc
    100: wordcloud_rep
     99: renderPlot [C:\Users\nyvad\Google Drive\R-API\Twitter-Analysis-Shiny-App-master/server.R#60]
     89: <reactive:plotObj>
     78: plotObj
     77: origRenderFunc
     76: output$plot
      1: shiny::runApp

i search Nike

**Comment by dr-rodriguez** [comment]
This is a recurring error with some searches (see https://github.com/dr-rodriguez/Twitter-Analysis-Shiny-App/issues/1). Unfortunately, nulls in strings are a known limitation of R.
